#!/bin/bash

OUTPUT_DIR="target"

build() {
    if [ ! -d $OUTPUT_DIR ]; then
        mkdir $OUTPUT_DIR
    fi
    cd target
    cmake -DCMAKE_BUILD_TYPE=Debug ..
    cmake --build . --config Debug
}

release() {
    if [ ! -d $OUTPUT_DIR ]; then
        mkdir $OUTPUT_DIR
    fi
    cd $OUTPUT_DIR
    cmake -DCMAKE_BUILD_TYPE=Release ..
    cmake --build . --config Release
}

run() {
    build
    ./debug/Raytracing
}

if [ "$1" == "run" ]; then
    run

elif [ "$1" == "clean" ]; then
    rm -rf $OUTPUT_DIR
    echo "Cleaned build directory"

elif [ "$1" == "release" ]; then
    release
    echo "Release build completed"

else
    build
    echo "Debug build completed"
fi

